import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '../components/Screen';
import { TradeCard } from '../components/TradeCard';
import { SummaryCard } from '../components/SummaryCard';
import { mockTrades } from '../data/mockTrades';
import { RootStackParamList } from '../navigation/types';
import { colors } from '../theme/colors';
import { formatCompactCurrency } from '../utils/formatters';
import { getLatestTrades, getTopSignalTrades, summarizeTrades } from '../utils/filterTrades';
type Props=NativeStackScreenProps<RootStackParamList,'Home'>;
export function HomeScreen({navigation}:Props){const summary=summarizeTrades(mockTrades);const latest=getLatestTrades(mockTrades);const topSignals=getTopSignalTrades(mockTrades);return <Screen testID="home-screen">
  <View style={s.header}><View><Text style={s.eyebrow}>SIGNALSCOPE</Text><Text style={s.title}>Market Pulse</Text></View><View style={s.demo}><Text style={s.demoText}>● FICTIONAL DATA</Text></View></View>
  <Text style={s.intro}>A calm snapshot of invented insider activity—built for demonstration, never investment decisions.</Text>
  <Pressable accessibilityRole="search" accessibilityLabel="Search ticker or company" onPress={()=>navigation.navigate('Screener',{focusSearch:true})} style={s.search}><Text style={s.searchIcon}>⌕</Text><Text style={s.searchText}>Search ticker or company</Text><Text style={s.arrow}>›</Text></Pressable>
  <View style={s.summaries}><SummaryCard value={`${summary.count}`} label="demo filings"/><SummaryCard value={formatCompactCurrency(summary.purchases)} label="purchases" tone="purchase"/><SummaryCard value={formatCompactCurrency(summary.sales)} label="sales" tone="sale"/></View>
  <View style={s.section}><Text style={s.sectionTitle}>Top signals</Text><Text style={s.hint}>Today · demo</Text></View><View style={s.signalPanel}>{topSignals.map((trade,i)=><Pressable accessibilityRole="button" accessibilityLabel={`Open ${trade.signal} for ${trade.company}`} onPress={()=>navigation.navigate('TradeDetails',{tradeId:trade.id})} style={({pressed})=>[s.signalRow,pressed&&s.pressed]} key={trade.id}><Text style={s.signalNumber}>0{i+1}</Text><View style={s.signalCopy}><Text style={s.signalName}>{trade.signal}</Text><Text style={s.signalMeta}>{trade.ticker} · {formatCompactCurrency(trade.value)} demo</Text></View><Text style={s.arrow}>›</Text></Pressable>)}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Latest activity</Text><Pressable accessibilityRole="button" accessibilityLabel="View all fictional trades" onPress={()=>navigation.navigate('Screener')} hitSlop={10}><Text style={s.link}>View all</Text></Pressable></View><View style={s.list}>{latest.map(t=><TradeCard key={t.id} trade={t} onPress={()=>navigation.navigate('TradeDetails',{tradeId:t.id})}/>)}</View>
  <Pressable accessibilityRole="button" style={({pressed})=>[s.cta,pressed&&s.pressed]} onPress={()=>navigation.navigate('Screener')}><Text style={s.ctaText}>Browse all fictional trades</Text><Text style={s.ctaText}>→</Text></Pressable>
  </Screen>}
const s=StyleSheet.create({header:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{color:colors.analytics,fontSize:11,fontWeight:'900',letterSpacing:2},title:{color:colors.text,fontSize:31,fontWeight:'900'},demo:{backgroundColor:colors.warningBg,borderRadius:99,paddingHorizontal:10,paddingVertical:7},demoText:{color:'#CBC2FF',fontSize:9,fontWeight:'900'},intro:{color:colors.textMuted,fontSize:14,lineHeight:21,marginTop:10,maxWidth:560},search:{minHeight:54,marginTop:24,paddingHorizontal:16,borderRadius:16,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center'},pressed:{opacity:.72},searchIcon:{color:colors.analytics,fontSize:25,marginRight:10},searchText:{flex:1,color:colors.textMuted,fontSize:14},arrow:{color:colors.textMuted,fontSize:24},summaries:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:14},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:28,marginBottom:12},sectionTitle:{color:colors.text,fontSize:19,fontWeight:'800'},hint:{color:colors.textMuted,fontSize:12},link:{color:colors.analytics,fontWeight:'800'},signalPanel:{borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,overflow:'hidden'},signalRow:{minHeight:66,paddingHorizontal:14,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},signalNumber:{color:colors.analytics,fontSize:11,fontWeight:'900',width:36},signalCopy:{flex:1,gap:3},signalName:{color:colors.text,fontSize:14,fontWeight:'700'},signalMeta:{color:colors.textMuted,fontSize:11},list:{gap:12},cta:{minHeight:54,borderRadius:16,marginTop:16,paddingHorizontal:18,backgroundColor:colors.analytics,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},ctaText:{color:colors.background,fontWeight:'900'}});
