import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { TradeCard } from '../components/TradeCard';
import { mockTrades } from '../data/mockTrades';
import { RootStackParamList } from '../navigation/types';
import { colors } from '../theme/colors';
import { formatCompactCurrency } from '../utils/formatters';
import { summarizeTrades } from '../utils/filterTrades';
type Props=NativeStackScreenProps<RootStackParamList,'Home'>;
export function HomeScreen({navigation}:Props){const summary=summarizeTrades(mockTrades);const latest=[...mockTrades].sort((a,b)=>b.filedAt.localeCompare(a.filedAt)).slice(0,4);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
  <View style={s.header}><View><Text style={s.eyebrow}>SIGNALSCOPE</Text><Text style={s.title}>Market Pulse</Text></View><View style={s.demo}><Text style={s.demoText}>● FICTIONAL DATA</Text></View></View>
  <Text style={s.intro}>A calm snapshot of invented insider activity—built for demonstration, never investment decisions.</Text>
  <Pressable accessibilityRole="search" accessibilityLabel="Search ticker or company" onPress={()=>navigation.navigate('Screener',{focusSearch:true})} style={s.search}><Text style={s.searchIcon}>⌕</Text><Text style={s.searchText}>Search ticker or company</Text><Text style={s.arrow}>›</Text></Pressable>
  <View style={s.summaries}>{[[`${summary.count}`,'demo filings',colors.analytics],[formatCompactCurrency(summary.purchases),'purchases',colors.purchase],[formatCompactCurrency(summary.sales),'sales',colors.sale]].map(([v,l,c])=><View key={l} style={s.summary}><View style={[s.dot,{backgroundColor:c}]}/><Text style={s.summaryValue}>{v}</Text><Text style={s.summaryLabel}>{l}</Text></View>)}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Top signals</Text><Text style={s.hint}>Today · demo</Text></View><View style={s.signalPanel}>{['Large CEO Purchase','Cluster Buy','Executive Sale'].map((x,i)=><View style={s.signalRow} key={x}><Text style={s.signalNumber}>0{i+1}</Text><Text style={s.signalName}>{x}</Text><Text style={s.arrow}>›</Text></View>)}</View>
  <View style={s.section}><Text style={s.sectionTitle}>Latest activity</Text><Pressable onPress={()=>navigation.navigate('Screener')} hitSlop={10}><Text style={s.link}>View all</Text></Pressable></View><View style={s.list}>{latest.map(t=><TradeCard key={t.id} trade={t} onPress={()=>navigation.navigate('TradeDetails',{tradeId:t.id})}/>)}</View>
  <Pressable accessibilityRole="button" style={s.cta} onPress={()=>navigation.navigate('Screener')}><Text style={s.ctaText}>Browse all fictional trades</Text><Text style={s.ctaText}>→</Text></Pressable>
  </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:20,paddingBottom:40},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{color:colors.analytics,fontSize:11,fontWeight:'900',letterSpacing:2},title:{color:colors.text,fontSize:31,fontWeight:'900'},demo:{backgroundColor:colors.warningBg,borderRadius:99,paddingHorizontal:10,paddingVertical:7},demoText:{color:'#CBC2FF',fontSize:9,fontWeight:'900'},intro:{color:colors.textMuted,fontSize:14,lineHeight:21,marginTop:10},search:{minHeight:54,marginTop:24,paddingHorizontal:16,borderRadius:16,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center'},searchIcon:{color:colors.analytics,fontSize:25,marginRight:10},searchText:{flex:1,color:colors.textMuted,fontSize:14},arrow:{color:colors.textMuted,fontSize:24},summaries:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:14},summary:{flex:1,minWidth:104,padding:14,borderRadius:16,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,gap:5},dot:{width:7,height:7,borderRadius:4,marginBottom:4},summaryValue:{color:colors.text,fontSize:20,fontWeight:'900'},summaryLabel:{color:colors.textMuted,fontSize:12},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:28,marginBottom:12},sectionTitle:{color:colors.text,fontSize:19,fontWeight:'800'},hint:{color:colors.textMuted,fontSize:12},link:{color:colors.analytics,fontWeight:'800'},signalPanel:{borderRadius:18,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,overflow:'hidden'},signalRow:{minHeight:58,paddingHorizontal:14,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},signalNumber:{color:colors.analytics,fontSize:11,fontWeight:'900',width:36},signalName:{flex:1,color:colors.text,fontSize:14,fontWeight:'700'},list:{gap:12},cta:{minHeight:54,borderRadius:16,marginTop:16,paddingHorizontal:18,backgroundColor:colors.analytics,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},ctaText:{color:colors.background,fontWeight:'900'}});
